version: "3"

services:
  database:
    container_name: database
    image: "postgres:13"
    restart: always
    env_file: 
      - ./prod.env
    volumes:
      - /home/serverdata-prod/:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./dockerfile.prod
    env_file: 
      - ./prod.env
    ports: 
      - "7002:1437"
    depends_on: 
      - database
    restart: always
