version: "3"

services:
  database:
    container_name: database
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: biddytime
    ports: 
      - "7000:5432"
    volumes:
      - /home/serverdata/:/var/lib/postgresql/data
  
  adminer:
    image: "adminer"
    restart: always
    depends_on: 
      - database
    ports:
      - "7001:8080"

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./dockerfile
    environment: 
      - NODE_ENV=development
      - JWT_SECRET=keepitsecretkeepitsafe
    volumes: 
      - ./:/usr/src/app
    ports: 
      - "7002:1437"
    depends_on: 
      - database
    restart: always
