name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 15.x
      - run: yarn install
      - run: yarn build
      - run: docker build -f ./dockerfile.prod -t biddytime-backend:latest .
      - name: Push to github packages
      - run: echo ${{ secrets.REPO_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
